# Generated by Django 4.0.4 on 2022-06-05 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='proffessor',
        ),
    ]
