# Generated by Django 4.0.4 on 2022-06-06 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_stu_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='prof_course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courses', models.ManyToManyField(blank=True, to='base.course')),
                ('prof_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professor', to='base.course')),
            ],
        ),
    ]
