# Generated by Django 4.0.4 on 2022-06-06 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_prof_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prof_course',
            name='prof_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.professor'),
        ),
    ]
